// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/docs/associations.tsx";
import * as $1 from "./routes/docs/development.tsx";
import * as $2 from "./routes/docs/getting-started.tsx";
import * as $3 from "./routes/docs/methods.tsx";
import * as $4 from "./routes/docs/model.tsx";
import * as $5 from "./routes/gui/api/getConnections.tsx";
import * as $6 from "./routes/gui/api/handleConnectionSave.ts";
import * as $7 from "./routes/gui/api/handleModelSave.ts";
import * as $8 from "./routes/gui/api/handleQueryRun.ts";
import * as $9 from "./routes/gui/api/handleQuerySave.ts";
import * as $10 from "./routes/gui/api/signIn.tsx";
import * as $11 from "./routes/gui/api/signUp.tsx";
import * as $12 from "./routes/gui/api/writeUriToFile.ts";
import * as $13 from "./routes/gui/connections.tsx";
import * as $14 from "./routes/gui/explorer.tsx";
import * as $15 from "./routes/gui/home.tsx";
import * as $16 from "./routes/gui/index.tsx";
import * as $17 from "./routes/gui/migrations.tsx";
import * as $18 from "./routes/index.tsx";
import * as $$0 from "./islands/Connections.tsx";
import * as $$1 from "./islands/Console.tsx";
import * as $$2 from "./islands/DocsNav.tsx";
import * as $$3 from "./islands/Login.tsx";
import * as $$4 from "./islands/Migrations.tsx";
import * as $$5 from "./islands/NavBar.tsx";

const manifest = {
  routes: {
    "./routes/docs/associations.tsx": $0,
    "./routes/docs/development.tsx": $1,
    "./routes/docs/getting-started.tsx": $2,
    "./routes/docs/methods.tsx": $3,
    "./routes/docs/model.tsx": $4,
    "./routes/gui/api/getConnections.tsx": $5,
    "./routes/gui/api/handleConnectionSave.ts": $6,
    "./routes/gui/api/handleModelSave.ts": $7,
    "./routes/gui/api/handleQueryRun.ts": $8,
    "./routes/gui/api/handleQuerySave.ts": $9,
    "./routes/gui/api/signIn.tsx": $10,
    "./routes/gui/api/signUp.tsx": $11,
    "./routes/gui/api/writeUriToFile.ts": $12,
    "./routes/gui/connections.tsx": $13,
    "./routes/gui/explorer.tsx": $14,
    "./routes/gui/home.tsx": $15,
    "./routes/gui/index.tsx": $16,
    "./routes/gui/migrations.tsx": $17,
    "./routes/index.tsx": $18,
  },
  islands: {
    "./islands/Connections.tsx": $$0,
    "./islands/Console.tsx": $$1,
    "./islands/DocsNav.tsx": $$2,
    "./islands/Login.tsx": $$3,
    "./islands/Migrations.tsx": $$4,
    "./islands/NavBar.tsx": $$5,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
